# FreeLinX/ports - sysutils/flx-tools : FreeLinX Core Desktop Utilities & Tools
# Suite including flx-fm, flx-panel, flx-view, flx-shot, flx-3dtest, flx-bg.

NAME    := flx-tools
VERSION := 1.0
CATEGORY:= sysutils
LICENSE := MIT
TARGET  := $(FREELINX_TRIPLE)
PREFIX  := /usr

INSTALL_BIN:= flx-fm
INSTALL_RELPATH:= usr/bin/flx-fm

include ../../mk/project-port.mk
