# FreeLinX/ports - base/echo : NetBSD `echo`.
NAME   := echo
VERSION:= 10.1
CATEGORY:= base
LICENSE:= BSD-2-Clause
DEPENDENCIES:=
BUILD_DEPENDENCIES:=
TARGET := $(FREELINX_TRIPLE)
PREFIX := /

SRC_DIR  = $(FREELINX_BUILD_DIR)/work/$(NAME)
BUILD_BIN = $(SRC_DIR)/$(NAME)

include ../../mk/base-port.mk
