# FreeLinX/ports - editors/flxt : 1990s Unix Motif/X11 Text Editor
# Modeless, lightweight, fast text editor with 16-color ANSI syntax.

NAME    := flxt
VERSION := 1.0
CATEGORY:= editors
LICENSE := MIT
TARGET  := $(FREELINX_TRIPLE)
PREFIX  := /usr

INSTALL_BIN:= flxt
INSTALL_RELPATH:= usr/bin/flxt

include ../../mk/project-port.mk
